---
name: Convert-Cisco
version: 0.05
author:
  - "Mark O'Connor <marko@cpan.org>"
abstract: Module for converting Cisco billing records
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  DateTime: 0
  Log::Log4perl: 0
  Test::More: 0
  Test::Unit: 0
  XML::Writer: 0
  YAML::Syck: 0
provides:
  Convert::Cisco:
    file: lib/Convert/Cisco.pm
    version: 0.05
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
